name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable nightly
          rustup component add --toolchain stable clippy
          rustup component add --toolchain nightly rustfmt
          rustup default stable

      - name: Install port audio
        run: |
          sudo apt-get -y install libasound2-dev

      - name: Run fmt
        if: always()
        run: cargo +nightly fmt -- --check

      - name: Run clippy
        if: always()
        run: cargo clippy -- -D warnings

      - name: Set environment variables
        if: always()
        run: |
          echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Run tests
        if: always()
        run: cargo test --verbose

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Commit images generated by unit test [skip actions]" || echo "No changes to commit"
          git push
