name: CI

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: CI
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Run fmt
        if: always()
        run: cargo +nightly fmt -- --check

      - name: Run clippy
        if: always()
        run: cargo clippy -- -D warnings

      - name: Set environment variables
        if: always()
        run: |
          echo "GIT_SHA=${{ github.sha }}" >> $Env:GITHUB_ENV

      - name: Run tests
        if: always()
        run: |
          cargo test --verbose

      - name: Commit generated files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: powershell
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet
          if ($LASTEXITCODE -ne 0) {
            git commit -m "Commit images generated by unit test [skip actions]"
            git push
          } else {
            Write-Output "No changes to commit"
          }
